### ISSUE TITLE
Use Microsoft Map data

### ISSUE THREAD

**Issue by albusmw** [AlexanderKrutov/WinFormsMapControl#1]
Hi, I just started using your control and it works fine.
BUT: Can I also use the Microsoft Maps in the control? I downloaded some content for it offline, but want to feed my own data in the map and not use the GPS receiver (as I want to do some stuff with the GPS data and just pass the position to the map).

And idea?

Regards Martin.

**Comment by AlexanderKrutov** [comment]
Hi Martin!
Thank you for the feedback.
There are no Microsoft Maps support out if the box, but you can try to write own class to handle tile server, see docs:
https://github.com/AlexanderKrutov/WinFormsMapControl/blob/master/Docs/TileServer.md
You need to override `GetTileUri(int x, int y, int z)` method and return a valid uri to the map tile.

Here is a some starting point about tile system of MS Maps:
https://docs.microsoft.com/en-us/bingmaps/rest-services/directly-accessing-the-bing-maps-tiles
https://docs.microsoft.com/en-us/bingmaps/articles/bing-maps-tile-system

Also you need to convert x,y,z to quadkey:

```csharp
public static string TileXYToQuadKey(int tileX, int tileY, int zoom)
{
	var quadKey = new StringBuilder();
	for (int i = zoom; i > 0; i--)
	{
		char digit = '0';
		int mask = 1 << (i - 1);
		if ((tileX & mask) != 0)
		{
			digit++;
		}
		if ((tileY & mask) != 0)
		{
			digit++;
			digit++;
		}
		quadKey.Append(digit);
	}
	return quadKey.ToString();
}
```
See more here: https://docs.microsoft.com/en-us/azure/azure-maps/zoom-levels-and-tile-grid?tabs=csharp

Please also note that some tile providers limit or even prohibit usage of their tiles by third party software (not sure about Microsoft Maps though).

**Comment by AlexanderKrutov** [comment]
By the way, I've added MS Maps support, so I suppose the issue can be closed.
See: 
https://github.com/AlexanderKrutov/WinFormsMapControl/blob/master/MapControl/TileServers/BingMapsTileServer.cs
